noson: NSROOT::RequestBroker Class Reference
NSROOT::RequestBroker Class Reference abstract
Data Structures
struct handle
struct Resource
Public Types
typedef SHARED_PTR< Resource > ResourcePtr
typedef std::list< ResourcePtr > ResourceList
Public Member Functions
virtual bool Initialize ()
The initializer of the broker. It should return false when the feature cannot be activated on the running platform. The default implementation return true.
virtual bool HandleRequest (handle *handle)=0
Handle an incoming request.
virtual const char * CommonName ()=0
Return the common name for this handler.
virtual ResourcePtr GetResource (const std::string &title)=0
virtual ResourceList GetResourceList ()=0
virtual ResourcePtr RegisterResource (const std::string &title, const std::string &description, const std::string &path, StreamReader *delegate)=0
virtual void UnregisterResource (const std::string &uri)=0
void Abort ()
bool IsAborted ()
unsigned Count200 ()
unsigned Count400 ()
unsigned Count404 ()
unsigned Count429 ()
unsigned Count500 ()
unsigned Count503 ()
Protected Types
enum Status {
Status_OK , Status_Partial_Content , Status_Bad_Request , Status_Not_Found ,
Status_Too_Many_Requests , Status_Internal_Server_Error , Status_Service_Unavailable
}
enum Method {
Method_GET , Method_POST , Method_HEAD , Method_SUBSCRIBE ,
Method_UNSUBSCRIBE , Method_NOTIFY , Method_UNKNOWN
}
Protected Member Functions
std::string MakeResponseHeader (Status status)
Create the top header lines for the reply.
Static Protected Member Functions
static bool Reply (handle *handle, const char *data, size_t size)
Reply to the requester.
static Method GetRequestMethod (handle *handle)
static const std::string & GetRequestURI (handle *handle)
static const std::string & GetRequestProtocol (handle *handle)
static const std::string & GetRequestHeader (handle *handle, const std::string &name)
static bool HasContent (handle *handle)
static size_t GetContentLength (handle *handle)
static size_t GetConsumed (handle *handle)
static size_t ReadContent (handle *handle, std::string &data)
Read data from the request content.
static std::string buildDelegateUrl (const Resource &res, const std::string &uri)
Helper to build the delegate url from a call uri.
static std::string buildUri (const std::string &rootUri, const std::string &path)
Helper to build uri from the given root and path.
Private Attributes
bool m_aborted
IntrinsicCounter m_200
IntrinsicCounter m_400
IntrinsicCounter m_404
IntrinsicCounter m_429
IntrinsicCounter m_500
IntrinsicCounter m_503
Detailed Description
Definition at line 41 of file requestbroker.h.
Member Typedef Documentation
ResourceList
typedef std::list<ResourcePtr> NSROOT::RequestBroker::ResourceList
Definition at line 88 of file requestbroker.h.
ResourcePtr
typedef SHARED_PTR<Resource> NSROOT::RequestBroker::ResourcePtr
Definition at line 87 of file requestbroker.h.
Member Enumeration Documentation
Method
enum NSROOT::RequestBroker::Method protected
Definition at line 136 of file requestbroker.h.
Status
enum NSROOT::RequestBroker::Status protected
Definition at line 109 of file requestbroker.h.
Constructor & Destructor Documentation
RequestBroker()
RequestBroker::RequestBroker ()
Definition at line 30 of file requestbroker.cpp.
~RequestBroker()
RequestBroker::~RequestBroker () virtual
Definition at line 41 of file requestbroker.cpp.
Member Function Documentation
Abort()
void NSROOT::RequestBroker::Abort () inline
Definition at line 98 of file requestbroker.h.
buildDelegateUrl()
std::string RequestBroker::buildDelegateUrl (const Resource & res, const std::string & uri) static protected
Helper to build the delegate url from a call uri.
Parameters
res the delegated resource
uri the call uri
Returns
the valid url to pass to the delegate
Definition at line 146 of file requestbroker.cpp.
References NSROOT::RequestBroker::Resource::sourcePath.
buildUri()
std::string RequestBroker::buildUri (const std::string & rootUri, const std::string & path) static protected
Helper to build uri from the given root and path.
Parameters
rootUri the root uri
path the path to add
Returns
the uri
Definition at line 154 of file requestbroker.cpp.
CommonName()
virtual const char * NSROOT::RequestBroker::CommonName () pure virtual
Return the common name for this handler.
Returns
the common name
Implemented in NSROOT::FileStreamer, NSROOT::ImageService, and NSROOT::PulseStreamer.
Count200()
unsigned NSROOT::RequestBroker::Count200 () inline
Definition at line 100 of file requestbroker.h.
Count400()
unsigned NSROOT::RequestBroker::Count400 () inline
Definition at line 101 of file requestbroker.h.
Count404()
unsigned NSROOT::RequestBroker::Count404 () inline
Definition at line 102 of file requestbroker.h.
Count429()
unsigned NSROOT::RequestBroker::Count429 () inline
Definition at line 103 of file requestbroker.h.
Count500()
unsigned NSROOT::RequestBroker::Count500 () inline
Definition at line 104 of file requestbroker.h.
Count503()
unsigned NSROOT::RequestBroker::Count503 () inline
Definition at line 105 of file requestbroker.h.
GetConsumed()
size_t RequestBroker::GetConsumed (handle * handle) static protected
Parameters
handle
Returns
The size in byte read from the content
Definition at line 126 of file requestbroker.cpp.
GetContentLength()
size_t RequestBroker::GetContentLength (handle * handle) static protected
Parameters
handle
Returns
The size in byte of the content of the request
Definition at line 120 of file requestbroker.cpp.
GetRequestHeader()
const std::string & RequestBroker::GetRequestHeader (handle * handle, const std::string & name) static protected
Parameters
handle
Returns
The value of the requet header with the given name
Definition at line 108 of file requestbroker.cpp.
Referenced by NSROOT::FileStreamer::HandleRequest().
GetRequestMethod()
RequestBroker::Method RequestBroker::GetRequestMethod (handle * handle) static protected
Parameters
handle
Returns
The method invoked by the request
Definition at line 74 of file requestbroker.cpp.
Referenced by NSROOT::FileStreamer::HandleRequest(), NSROOT::ImageService::HandleRequest(), and NSROOT::PulseStreamer::HandleRequest().
GetRequestProtocol()
const std::string & RequestBroker::GetRequestProtocol (handle * handle) static protected
Parameters
handle
Returns
The protocol of the request, i.e HTTP/1.1
Definition at line 102 of file requestbroker.cpp.
GetRequestURI()
const std::string & RequestBroker::GetRequestURI (handle * handle) static protected
Parameters
handle
Returns
The URI intended by the request
Definition at line 96 of file requestbroker.cpp.
Referenced by NSROOT::FileStreamer::HandleRequest(), NSROOT::ImageService::HandleRequest(), and NSROOT::PulseStreamer::HandleRequest().
HandleRequest()
virtual bool NSROOT::RequestBroker::HandleRequest (handle * handle) pure virtual
Handle an incoming request.
Parameters
handle the data to pass for callback
uri the URI of the requested resource
Returns
true if the request is processed, else false
Implemented in NSROOT::FileStreamer, NSROOT::ImageService, and NSROOT::PulseStreamer.
HasContent()
bool RequestBroker::HasContent (handle * handle) static protected
Parameters
handle
Returns
true is the request has a content, else false
Definition at line 114 of file requestbroker.cpp.
Initialize()
bool RequestBroker::Initialize () virtual
The initializer of the broker. It should return false when the feature cannot be activated on the running platform. The default implementation return true.
Returns
true if succeeded, else false
Reimplemented in NSROOT::PulseStreamer.
Definition at line 45 of file requestbroker.cpp.
IsAborted()
bool NSROOT::RequestBroker::IsAborted () inline
Definition at line 99 of file requestbroker.h.
MakeResponseHeader()
std::string RequestBroker::MakeResponseHeader (Status status) protected
Create the top header lines for the reply.
Parameters
status
Returns
The response header for the given status code
Definition at line 47 of file requestbroker.cpp.
Referenced by NSROOT::FileStreamer::HandleRequest(), and NSROOT::PulseStreamer::HandleRequest().
ReadContent()
size_t RequestBroker::ReadContent (handle * handle, std::string & data) static protected
Read data from the request content.
Parameters
handle
data The string buffer to append read data
Returns
The size in byte read from the content
Definition at line 132 of file requestbroker.cpp.
Reply()
bool RequestBroker::Reply (handle * handle, const char * data, size_t size) static protected
Reply to the requester.
Parameters
handle
data the buffer containing bytes to send
size the size of data
Returns
true is all data have been sent, else false
Definition at line 68 of file requestbroker.cpp.
Referenced by NSROOT::FileStreamer::HandleRequest(), and NSROOT::PulseStreamer::HandleRequest().
Field Documentation
m_200
IntrinsicCounter NSROOT::RequestBroker::m_200 private
Definition at line 215 of file requestbroker.h.
m_400
IntrinsicCounter NSROOT::RequestBroker::m_400 private
Definition at line 216 of file requestbroker.h.
m_404
IntrinsicCounter NSROOT::RequestBroker::m_404 private
Definition at line 217 of file requestbroker.h.
m_429
IntrinsicCounter NSROOT::RequestBroker::m_429 private
Definition at line 218 of file requestbroker.h.
m_500
IntrinsicCounter NSROOT::RequestBroker::m_500 private
Definition at line 219 of file requestbroker.h.
m_503
IntrinsicCounter NSROOT::RequestBroker::m_503 private
Definition at line 220 of file requestbroker.h.
m_aborted
bool NSROOT::RequestBroker::m_aborted private
Definition at line 214 of file requestbroker.h.
The documentation for this class was generated from the following files:
/home/rowan/code/sonos-tui/noson/noson/src/requestbroker.h
/home/rowan/code/sonos-tui/noson/noson/src/requestbroker.cpp