noson: NSROOT::PulseStreamer Class Reference
NSROOT::PulseStreamer Class Reference
Public Member Functions
PulseStreamer (RequestBroker *imageService=nullptr)
virtual bool Initialize () override
The initializer of the broker. It should return false when the feature cannot be activated on the running platform. The default implementation return true.
virtual bool HandleRequest (handle *handle) override
Handle an incoming request.
const char * CommonName () override
Return the common name for this handler.
RequestBroker::ResourcePtr GetResource (const std::string &title) override
RequestBroker::ResourceList GetResourceList () override
RequestBroker::ResourcePtr RegisterResource (const std::string &title, const std::string &description, const std::string &path, StreamReader *delegate) override
void UnregisterResource (const std::string &uri) override
Public Member Functions inherited from NSROOT::RequestBroker
virtual bool Initialize ()
The initializer of the broker. It should return false when the feature cannot be activated on the running platform. The default implementation return true.
virtual bool HandleRequest (handle *handle)=0
Handle an incoming request.
virtual const char * CommonName ()=0
Return the common name for this handler.
virtual ResourcePtr GetResource (const std::string &title)=0
virtual ResourceList GetResourceList ()=0
virtual ResourcePtr RegisterResource (const std::string &title, const std::string &description, const std::string &path, StreamReader *delegate)=0
virtual void UnregisterResource (const std::string &uri)=0
void Abort ()
bool IsAborted ()
unsigned Count200 ()
unsigned Count400 ()
unsigned Count404 ()
unsigned Count429 ()
unsigned Count500 ()
unsigned Count503 ()
Private Member Functions
std::string GetPASink ()
void FreePASink ()
void streamSink (handle *handle)
void Reply503 (handle *handle)
void Reply400 (handle *handle)
void Reply429 (handle *handle)
Private Attributes
ResourceList m_resources
LockedNumber< unsigned > m_sinkIndex
LockedNumber< int > m_playbackCount
Additional Inherited Members
Public Types inherited from NSROOT::RequestBroker
typedef SHARED_PTR< Resource > ResourcePtr
typedef std::list< ResourcePtr > ResourceList
Protected Types inherited from NSROOT::RequestBroker
enum Status {
Status_OK , Status_Partial_Content , Status_Bad_Request , Status_Not_Found ,
Status_Too_Many_Requests , Status_Internal_Server_Error , Status_Service_Unavailable
}
enum Method {
Method_GET , Method_POST , Method_HEAD , Method_SUBSCRIBE ,
Method_UNSUBSCRIBE , Method_NOTIFY , Method_UNKNOWN
}
Protected Member Functions inherited from NSROOT::RequestBroker
std::string MakeResponseHeader (Status status)
Create the top header lines for the reply.
Static Protected Member Functions inherited from NSROOT::RequestBroker
static bool Reply (handle *handle, const char *data, size_t size)
Reply to the requester.
static Method GetRequestMethod (handle *handle)
static const std::string & GetRequestURI (handle *handle)
static const std::string & GetRequestProtocol (handle *handle)
static const std::string & GetRequestHeader (handle *handle, const std::string &name)
static bool HasContent (handle *handle)
static size_t GetContentLength (handle *handle)
static size_t GetConsumed (handle *handle)
static size_t ReadContent (handle *handle, std::string &data)
Read data from the request content.
static std::string buildDelegateUrl (const Resource &res, const std::string &uri)
Helper to build the delegate url from a call uri.
static std::string buildUri (const std::string &rootUri, const std::string &path)
Helper to build uri from the given root and path.
Detailed Description
Definition at line 31 of file pulsestreamer.h.
Constructor & Destructor Documentation
PulseStreamer()
PulseStreamer::PulseStreamer (RequestBroker * imageService = nullptr)
Definition at line 46 of file pulsestreamer.cpp.
~PulseStreamer()
NSROOT::PulseStreamer::~PulseStreamer () inline override
Definition at line 35 of file pulsestreamer.h.
Member Function Documentation
CommonName()
const char * NSROOT::PulseStreamer::CommonName () inline override virtual
Return the common name for this handler.
Returns
the common name
Implements NSROOT::RequestBroker.
Definition at line 39 of file pulsestreamer.h.
FreePASink()
void PulseStreamer::FreePASink () private
Definition at line 185 of file pulsestreamer.cpp.
GetPASink()
std::string PulseStreamer::GetPASink () private
Definition at line 138 of file pulsestreamer.cpp.
GetResource()
RequestBroker::ResourcePtr PulseStreamer::GetResource (const std::string & title) override virtual
Implements NSROOT::RequestBroker.
Definition at line 107 of file pulsestreamer.cpp.
GetResourceList()
RequestBroker::ResourceList PulseStreamer::GetResourceList () override virtual
Implements NSROOT::RequestBroker.
Definition at line 113 of file pulsestreamer.cpp.
HandleRequest()
bool PulseStreamer::HandleRequest (handle * handle) override virtual
Handle an incoming request.
Parameters
handle the data to pass for callback
uri the URI of the requested resource
Returns
true if the request is processed, else false
Implements NSROOT::RequestBroker.
Definition at line 78 of file pulsestreamer.cpp.
References NSROOT::RequestBroker::GetRequestMethod(), NSROOT::RequestBroker::GetRequestURI(), NSROOT::RequestBroker::MakeResponseHeader(), and NSROOT::RequestBroker::Reply().
Initialize()
bool PulseStreamer::Initialize () override virtual
The initializer of the broker. It should return false when the feature cannot be activated on the running platform. The default implementation return true.
Returns
true if succeeded, else false
Reimplemented from NSROOT::RequestBroker.
Definition at line 71 of file pulsestreamer.cpp.
RegisterResource()
RequestBroker::ResourcePtr PulseStreamer::RegisterResource (const std::string & title, const std::string & description, const std::string & path, StreamReader * delegate) override virtual
Implements NSROOT::RequestBroker.
Definition at line 121 of file pulsestreamer.cpp.
Reply400()
void PulseStreamer::Reply400 (handle * handle) private
Definition at line 270 of file pulsestreamer.cpp.
Reply429()
void PulseStreamer::Reply429 (handle * handle) private
Definition at line 278 of file pulsestreamer.cpp.
Reply503()
void PulseStreamer::Reply503 (handle * handle) private
Definition at line 262 of file pulsestreamer.cpp.
streamSink()
void PulseStreamer::streamSink (handle * handle) private
Definition at line 203 of file pulsestreamer.cpp.
UnregisterResource()
void PulseStreamer::UnregisterResource (const std::string & uri) override virtual
Implements NSROOT::RequestBroker.
Definition at line 133 of file pulsestreamer.cpp.
Field Documentation
m_playbackCount
LockedNumber<int> NSROOT::PulseStreamer::m_playbackCount private
Definition at line 54 of file pulsestreamer.h.
m_resources
ResourceList NSROOT::PulseStreamer::m_resources private
Definition at line 49 of file pulsestreamer.h.
m_sinkIndex
LockedNumber<unsigned> NSROOT::PulseStreamer::m_sinkIndex private
Definition at line 52 of file pulsestreamer.h.
The documentation for this class was generated from the following files:
/home/rowan/code/sonos-tui/noson/noson/src/pulsestreamer.h
/home/rowan/code/sonos-tui/noson/noson/src/pulsestreamer.cpp